### ISSUE TITLE
你好，我想编译成libcurl.a 静态库，不知如何使用

### ISSUE THREAD

**Issue by BatterMan-Li** [vvb2060/curl-android#3]
现在c项目中使用curl 三方库，由于需要把C项目编译成so文件或者aar文件，依赖的curl库编译成Android不同架构的静态库，现在看到issues和workflows都没有看懂，麻烦能否指点下

**Comment by vvb2060** [comment]
implementation 'io.github.vvb2060.ndk:curl:7.83.0-h3'

**Comment by BatterMan-Li** [comment]
> implementation 'io.github.vvb2060.ndk:curl:7.83.0-h3'

你好，能否留个联系方式，想请教下你

**Comment by BatterMan-Li** [comment]
大佬，你好
目前，手中一个C项目依赖了curl，secp256k1等三方库，现在需要把三方库编译Android 不同架构的静态依赖到C项目中，然后再把C项目编译成so库或者aar文件供Android项目使用，现在在编译依赖的三方库curl、secp256k1等项目时，不知道如何交叉编译，查看你的项目和Issues中提问，都不知道如何入手！直接编译运行也是报https://github.com/vvb2060/curl-android/issues/2中的问题，麻烦指导下，谢谢！

**Comment by vvb2060** [comment]
https://google.github.io/prefab/

**Comment by BatterMan-Li** [comment]
> https://google.github.io/prefab/

原项目我都没有动，我看build.gradle已经添加了prefab，但是还是编译不通过，是我的使用有问题吗？
![image](https://user-images.githubusercontent.com/28614345/170851466-8b78287d-a37c-4d6f-b903-670a2555edd0.png)
