### ISSUE TITLE
verbose mode not writing log

### ISSUE THREAD

**Issue by gengjiawen** [vvb2060/curl-android#6]
```cpp
    CURL *curl = curl_easy_init();
    if(curl) {
        curl_easy_setopt(curl, CURLOPT_URL, "https://example.com");

        /* ask libcurl to show us the verbose output */
        curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

        /* Perform the request */
        curl_easy_perform(curl);
    }
```

Looks like nothing is logging to android logcat ? Is there a way forward to `__android_log_print`

**Comment by vvb2060** [comment]
This is not the place to ask how to use libcurl.

**Comment by vvb2060** [comment]
https://stackoverflow.com/questions/15337319

**Comment by gengjiawen** [comment]
Thx for sharing, I think this is a common problem when debugging curl. Do you accept a PR mention this in `README.md` ?
