### ISSUE TITLE
add network permission to AndroidManifest.xml

### ISSUE THREAD

**Issue by gengjiawen** [vvb2060/curl-android#7]
add network permission.
https://github.com/vvb2060/curl-android/blob/master/curl/src/main/AndroidManifest.xml

If app forget add, curl will fail with resolve host failed unlike java app indicate permerssion issue.

similar in okhttp:
https://github.com/square/okhttp/blob/76331ffe0024d5f8ca2f88a32c6ed3185a3ab716/okhttp-android/src/main/AndroidManifest.xml#L4

**Comment by vvb2060** [comment]
https://github.com/vvb2060/curl-android/commit/a3d4254960c6fee35f7fa7bf48436b644b4d5ece
