### ISSUE TITLE
Can you bundle c-ares and idn2 ?

### ISSUE THREAD

**Issue by llothar** [vvb2060/curl-android#9]
This will add support for real fast asynchronous DNS lookup and international domain names.
As far as i know this is still not integrated into CURL.

And maybe SSH2 to support SFTP and SCP so the feature set is almost complete.

**Comment by vvb2060** [comment]
The implementation of c-ares on Android is unacceptable and will not be built in until the Java API is replaced with the NDK API.  Users of this project can add their own.

**Comment by vvb2060** [comment]
OpenLDAP, heimdal, MIT Kerberos, libidn2, libssh2
I don't think anyone will use the above libraries on Android's libcurl, so they won't be built in due to Android's space limitations.
